# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
    tags:
    - '*'

jobs:
  build:
    needs: check-security
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: "Setup Node.js"
      uses: "actions/setup-node@v1"
      with:
        node-version: 16

    - name: Check cypress setup
      run: |
        npx cypress verify
        npx cypress info
        npx cypress version

    - name: Run cypress test
      uses: cypress-io/github-action@v2

    - name: Check http status code of production site
      uses: lakuapik/gh-actions-http-status@v1
      with:
        sites: '["https://calculadora-dan-pipe.herokuapp.com"]'
        expected: '[200]'

    - name: Dupicate-Line Remover Action
      uses: maharishi-coder/Duplicate-Line-Remover-Action@v1

  check-security:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Check security alerts
      run: |
        curl \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/Crivelente/${{github.repository}}/vulnerability-alerts

  create-release:

    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        tag: "v1.1.0"
        token: ${{ secrets.GITHUB_TOKEN }}

  check-failures:

    if: ${{ always() && (needs.build.result=='failure' || needs.check-security.result=='failure' || needs.create-release.result=='failure') }}
    needs: [build, check-security, create-release]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: create an issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Error on github action
          body: |
            ### Context
            [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          labels: "action-bug"