# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: "Setup Node.js"
      uses: "actions/setup-node@v1"
      with:
        node-version: 16

    - name: Check cypress setup
      run: |
        npx cypress verify
        npx cypress info
        npx cypress version

    - name: Run cypress test
      uses: cypress-io/github-action@v2

    - name: Check http status code of production site
      uses: lakuapik/gh-actions-http-status@v1
      with:
        sites: '["https://calculadora-dan-pipe.herokuapp.com"]'
        expected: '[200]'

    - name: Dupicate-Line Remover Action
      uses: maharishi-coder/Duplicate-Line-Remover-Action@v1


